_btn_newsletter_routing_control:
    resource: "@BtnNewsletterBundle/Resources/config/routing/control.yml"
    prefix: /control

_btn_newsletter_routing_front:
    resource: "@BtnNewsletterBundle/Resources/config/routing/front.yml"
    prefix: /
