services:
    btn_newsletter.provider.newsletter:
        class: %btn_base.provider.entity.class%
        parent: btn_base.provider.abstract_entity
        arguments: ['%btn_newsletter.newsletter.class%']
