services:
    btn.newsletter:
        class: Btn\NewsletterBundle\Model\NewsletterManager
        arguments:
            params: %btn_newsletter%
            formFactory: @form.factory
            em: @doctrine.orm.entity_manager

    btn_newsletter.menu_navbar.newsletter_item:
        class: %btn_admin.menu_item.class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "app.newsletter.name", "cp_newsletter", [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar.modules }
