services:
    btn.newsletter:
        class: Btn\NewsletterBundle\Model\NewsletterManager
        arguments:
            params: %btn_newsletter%
            formFactory: @form.factory
            em: @doctrine.orm.entity_manager

    btn_newsletter.btn_admin_menu_top_item:
        class: Knp\Menu\MenuItem
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "app.newsletter.name", "cp_newsletter", [], []]
        scope: request
        tags:
            - { name: btn_admin_menu_item , parent: btn_admin.menu_top_modules }
